doodle:
  usepad: false
  internalPadUrl: "http://etherpad:9001/"
  externalPadUrl: "http://etherpad.diverse-team.fr:9001/"
  padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  organizermail: "olivier.barais@gmail.com"
  tmpfolder: "/tmp/excelFiles"
quarkus:
  datasource:
    db-kind: mysql
    username: tlc
    password: tlc
    jdbc:
      url: jdbc:mysql://db:3306/tlc
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
#    database:
#      generation: none
#      globally-quoted-identifiers: true
  mailer:
    #from: test@quarkus.io
    from: ikounadi02@gmail.com
#    host: smtp.sendgrid.net
    host: mail
    port: 2525
#    port: 465
#    ssl: true
    username: "ikounadi02"
    password: "77169209"
    mock: false
